### ISSUE TITLE
Broken tutorial (synaptic integration)

### ISSUE THREAD

**Issue by borismarin** [tarelli/tutorials#6]
Clicking on the middle tutorial at http://opensourcebrain.org/tutorials (Simulating Synaptic Integration) leads to a broken (Houston we have a problem) project, entitled HH Tutorial.
<img width="1437" alt="screen shot 2018-04-03 at 17 05 35" src="https://user-images.githubusercontent.com/3452783/38273229-cf0174b0-3761-11e8-9796-1f799319bccc.png">

The log says

> org.geppetto.core.common.GeppettoInitializationException: org.geppetto.model.util.GeppettoVisitingException: org.geppetto.core.model.ModelInterpreterException: org.lemsml.jlems.core.sim.ContentError: No component found: network_MainenEtAl_PyramidalCell. Existing components:

**Comment by mattearnshaw** [comment]
https://github.com/OpenSourceBrain/tutorials/commit/790bc403d9eb029798e3de5dfbb808af013f0854
